export default {
    border: {
        radius: {
            sm: 4,
            md: 8,
            lg: 16,
            pill: 500,
            cirular: '50%',
        },
        width: {
            hairline: '1px',
            thin: '2px',
            thick: '4px',
            heavy: '8px',
        },
    },
    opacity: {
        level: {
            semiopaque: 0.8,
            intense: 0.6,
            medium: 0.4,
            light: 0.2,
            semitransparent: 0.1,
        },
    },
    shadow: {
        level1: '8px',
        level2: '24px',
        level3: '32px',
        level4: '48px',
    },
    spacing: {
        inset: {
            quarck: '4px',
            nano: '8px',
            xs: '16px',
            sm: '24px',
            md: '32px',
            lg: '40px',
        },
        squish: {
            quarck: '4px',
            nano: '8px',
            xs: '16px',
            sm: '24px',
            md: '32px',
            lg: '40px',
        },
        inline: {
            quarck: '4px',
            nano: '8px',
            xxxs: '16px',
            xxs: '24px',
            xs: '32px',
            sm: '40px',
            md: '48px',
            lg: '64px',
            xl: '80px',
        },
        stack: {
            quarck: '4px',
            nano: '8px',
            xxxs: '16px',
            xxs: '24px',
            xs: '32px',
            sm: '40px',
            md: '48px',
            lg: '56px',
            xl: '64px',
            xxl: '80px',
            xxxl: '120px',
            huge: '160px',
            giant: '200px',
        },
    },
    icon: {
        size: {
            sm: '8px',
            md: '16px',
            lg: '24px',
        },
    },
}